sudo: required
services:
    - docker

before_install:
    - docker build -t alexeykirinyuk/docker-react -f Dockerfile.dev .

script:
    - docker run alexeykirinyuk/docker-react -e CI=true npm run test